version: "3.3"

services:

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    ports:
      - '2181:2181'
    volumes:
      - "/home/mustafa/data/zookeeper:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9092:9092'
    volumes:
      - "/home/mustafa/data/kafka:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
  # kafkadrop:
  #   image: 'obsidiandynamics/kafdrop'
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - "/home/mustafa/data/kafka:/bitnami"
  #   environment:
  #     - KAFKA_BROKERCONNECT=kafka:9092
  #   depends_on:
  #     - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
