version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - /home/mustafa/data/mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
    depends_on:
      - mongo


