version: "3.3"
services:
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql #user is root
    volumes:
      - /home/mustafa/data/mysql:/var/lib/mysql
  adminer:
    image: "adminer:latest"
    ports:
      - "8083:8080"

